### PR TITLE
164796906 users like comment

### PR DESCRIPTION
**Pull request by ssanusi**
#### Description
The Pull Request add the feature of Like comment functionality

#### Type of change
 -  added model, controller,and route for like endpoint 

#### How Has This Been Tested?
 - navigate to the route ```/api/v1/comments/: id/like``` you will be required to log in to the application 

#### Checklist:
 - [x] Implement like comments functionality 
 - [x] Integration Testing

#### PT
[#164796906](https://www.pivotaltracker.com/story/show/164796906)

### CODE REVIEW

**Review by chikeozulumba — COMMENTED** [review]
Nice work @ssanusi LGTM

**Comment by micah-akpan** [comment]
LGTM

**Comment by Simplemart17** [comment]
LGTM @ssanusi

**Review by toluola — COMMENTED** [review]
LGTM

**Review by chikeozulumba — COMMENTED** [review]
Nice implementation @ssanusi 
LGTM

**Review by Temmyogunbo — APPROVED** [review]

**Pull request merged**
