### PR TITLE
164952118 Change TravisCI Build Badge

### PR DESCRIPTION
**Pull request by Simplemart17**
#### Description
- There is need to change the build badge of the repository to reflect the build status.
#### Type of change
- Bug fix
#### How Has This Been Tested?
- The branch has reflected the build status
#### Checklist:
- This change generate no new warning
#### PT
[#164952118](https://www.pivotaltracker.com/story/show/164952118)

### CODE REVIEW

**Review by micah-akpan — APPROVED** [review]
Looks good to me

**Review by toluola — APPROVED** [review]
This is good

**Review by Oluwaseyi000 — APPROVED** [review]
look good to me

**Review by chikeozulumba — APPROVED** [review]
Nice Work Done, Keep it up.

**Comment by Raymond-Osy** [comment]
LGTM

**Review by Temmyogunbo — APPROVED** [review]

**Pull request merged**
