### PR TITLE
164796881 Deploy Base Application To Heroku

### PR DESCRIPTION
**Pull request by chikeozulumba**
#### Description
This will enable other users access and use the application.
#### Type of change
- Add Heroku deployment configuration to .travis.yml
- Add a new line to .travis.yml
#### How Has This Been Tested?
- [x] [Staging](https://author-haven-stage.herokuapp.com/)
- [x] [Production](https://author-haven.herokuapp.com/)
#### Checklist:
- [x] Deployment pipeline for Authors-Haven on Heroku
- [x] Production project to pipeline
- [x] Staging/development project to pipeline
#### PIVOTAL TRACKER
[#164796881](https://www.pivotaltracker.com/story/show/164796881)

### CODE REVIEW

**Comment by ssanusi** [comment]
since we have app.js which is our server I suggest we write a test to confirm that the app is up, so that travis-CI can always run this test

**Comment by Raymond-Osy** [comment]
Hy @chikeozulumba , please check out your PR and fill in the remaining necessary fields

**Comment by chikeozulumba** [comment]
> Hy @chikeozulumba , please check out your PR and fill in the remaining necessary fields

**Comment by chikeozulumba** [comment]
> Hy @chikeozulumba, please check out your PR and fill in the remaining necessary fields

Noted, thanks

**Comment by chikeozulumba** [comment]
@Raymond-Osy Completed your recommendations.
Thanks.

**Review by ssanusi — APPROVED** [review]
approved

**Review by toluola — APPROVED** [review]

**Review by Simplemart17 — APPROVED** [review]

**Pull request merged**
