### PR TITLE
164796897 Users Should Be Able To Receive Notifications

### PR DESCRIPTION
**Pull request by chikeozulumba**
#### Description
Notifications give users to opportunity to know what they may have missed which may be important to them.
#### Type of change
- [ ] Bug Fix (a non-breaking change which fixes an issue)
- [x] New Feature (a non-breaking change that adds functionality)
- [ ] New Chore (a non-breaking change that adds functionality)
- [ ] Breaking Change (a fix or feature which would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update
#### How Has This Been Tested?
- [ ] End to End
- [x] Integration
#### Checklist:
- [x] Unit test
- [ ] Code coverage
#### PT
[#164796897](https://www.pivotaltracker.com/story/show/164796897)

### CODE REVIEW

**Comment by Simplemart17** [comment]
LGTM @chikeozulumba

**Comment by micah-akpan** [comment]
LGTM

**Review by ssanusi — COMMENTED** [review]
LGTM

**Comment by Oluwaseyi000** [comment]
lgtm

**Review by Temmyogunbo — APPROVED** [review]

**Pull request merged**
