### PR TITLE
#164873436 Setup Prettier for prettifying code

### PR DESCRIPTION
**Pull request by micah-akpan**
#### Description
Adds `prettier` to format code and ensure formatting consistencies across all files
#### Type of change
New feature (non-breaking change which adds functionality)
#### How Has This Been Tested?
This Implemented functionality was tested by formatting all specified files before a Git commit operation
#### Checklist:
My changes generate no new warnings
#### PT
[#164873436](https://www.pivotaltracker.com/story/show/164873436)

### CODE REVIEW

**Comment by ssanusi** [comment]
i can see you have a merge conflict from package-lock.json we might want to either remove it from the project files or we include it in .gitignore.

**Review by Simplemart17 — COMMENTED** [review]
For the pull request template, you might want to change **JIRA** to **Pivotal Tracker** since that is what we use. Thank you.

**Comment by toluola** [comment]
nice job...but remove the test script in the package.json or you just rebase to have the updated version of the develop branch. Thanks.

**Comment by micah-akpan** [comment]
> For the pull request template, you might want to change **JIRA** to **Pivotal Tracker** since that is what we use. Thank you.

Okay. Thanks for pointing that out

**Comment by micah-akpan** [comment]
> i can see you have a merge conflict from package-lock.json we might want to either remove it from the project files or we include it in .gitignore.

Okay. We will deliberate with the team to know what we will do. Thanks for pointing that out

**Review by toluola — DISMISSED** [review]

**Review by ssanusi — DISMISSED** [review]
approved Pull Request

**Review by Oluwaseyi000 — DISMISSED** [review]

**Review by Simplemart17 — DISMISSED** [review]

**Review by Simplemart17 — APPROVED** [review]

**Review by Oluwaseyi000 — APPROVED** [review]

**Review by toluola — APPROVED** [review]

**Comment by micah-akpan** [comment]
> i can see you have a merge conflict from package-lock.json we might want to either remove it from the project files or we include it in .gitignore.



> For the pull request template, you might want to change **JIRA** to **Pivotal Tracker** since that is what we use. Thank you.

Okay. Thanks for pointing that out

**Pull request merged**
